.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SQUIRRELMAIL-CONFIGURE 8 "October 8, 2003"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
squirrelmail-configure \- Interactively configure SquirrelMail
.SH SYNOPSIS
.B squirrelmail-configure
.SH DESCRIPTION
Use this interactive command to create or modify your
/etc/squirrelmail/config.php file. The program contains online help.
Alternatively, you can edit this file by hand. For that, you can use
config_default.php as a reference.
.SH AUTHOR
The SquirrelMail Project Team <squirrelmail-devel@lists.sourceforge.net>

This manual page was written by Sam Johnston <samj@aos.net.au>,
for the Debian GNU/Linux system (but may be used by others)

